
/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
*/
import React from 'react';
import { X, FileText } from 'lucide-react';

const LegalModal = ({ isOpen, onClose, appName = "SpriteForge" }) => {
  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4" role="dialog" aria-modal="true" aria-labelledby="legal-modal-title">
      <div className="absolute inset-0 modal-backdrop" onClick={onClose} role="button" tabIndex={-1} />
      <div className="card-style relative max-w-lg w-full z-10 transition-all duration-300 ease-in-out transform scale-95 data-[open]:scale-100 opacity-0 data-[open]:opacity-100 !p-6 sm:!p-8" data-open={isOpen ? '' : undefined}>
        <div className="flex items-center justify-between mb-6 sm:mb-8">
          <h2 id="legal-modal-title" className="font-display text-2xl text-[var(--text-primary)] flex items-center">
            <FileText size={28} className="mr-3 text-[var(--accent-gold)]" /> Legal Information ({appName})
          </h2>
          <button type="button" onClick={onClose} className="p-1.5 rounded-full text-[var(--text-secondary)] hover:text-[var(--text-primary)] hover:bg-[var(--bg-secondary)] transition-colors" aria-label="Close legal information dialog">
            <X size={22} />
          </button>
        </div>
        
        <div className="prose-modals max-h-[60vh] overflow-y-auto pr-2">
          <p>This is a placeholder for legal information regarding {appName}.</p>
          <p><strong>Disclaimer:</strong> {appName} is a tool that uses generative AI. The outputs (sprites, character art) are generated by AI models and should be reviewed carefully. You are responsible for the sprites you create and how you use them. Ensure you have the rights to any reference images or art styles you upload and that your use of generated sprites complies with all applicable laws and third-party rights (e.g., intellectual property, copyright for game assets).</p>
          <h3>Ownership and Licensing</h3>
          <p>Placeholder text about ownership of generated content and any applicable licenses. (e.g., "You own the sprites you create using {appName}, subject to the terms of the underlying AI models and any third-party content used. Consider the implications for commercial use of generated game assets.")</p>
          <h3>Acceptable Use Policy</h3>
          <p>Placeholder for acceptable use. (e.g., "Do not use {appName} to create content that is harmful, infringing, illegal, or violates the rights of others. This includes generating sprites that closely mimic copyrighted characters without permission.")</p>
          <p><em>This is not real legal advice. Consult with a legal professional for actual terms and conditions, especially if using generated sprites in commercial projects.</em></p>
        </div>

        <div className="flex justify-end gap-3 pt-6 mt-4 border-t border-[var(--border-color)]">
          <button type="button" onClick={onClose} className="button-secondary !px-6 !py-2.5">
            Close
          </button>
        </div>
      </div>
    </div>
  );
};

export default LegalModal;